### ISSUE TITLE
Error starting pivot@0.8.6

### ISSUE THREAD

**Issue by harel-e** [implydata/pivot#150]
After upgrading to version 0.8.6, I get the below error when starting pivot under Amazon Linux 64 bit.
0.8.5 works fine.
I didn't run into that issue when running under MacOS

/usr/lib/node_modules/imply-pivot/node_modules/plywood/build/plyqlParser.js:6353
      PREPARE: 1
      ^^^^^^^
SyntaxError: Duplicate data property in object literal not allowed in strict mode
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/imply-pivot/node_modules/plywood/build/plywood.js:10976:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by vogievetsky** [comment]
huh. this is an error indeed. `PREPARE` is duplicated. I am very confused about how it worked / is for me (and the unit tests).
Could you please tell me what node version you are running `node --version`
I am about to cut a version that would fix this but please do tell me the node version so I can figure out how this kind of thing can slip past the unit tests.

**Comment by vogievetsky** [comment]
Should work in 0.8.9

**Comment by harel-e** [comment]
>node --version
v0.10.42

**Comment by harel-e** [comment]
Version 0.8.9 works for me.

Thanks

**Comment by vogievetsky** [comment]
Oh wow. node 0.10 ... good times; fond memories. so maybe strict mode was turned off sometime between then and node 5.x
