### ISSUE TITLE
Search in filter tile causes exception in historical nodes

### ISSUE THREAD

**Issue by hollow** [implydata/pivot#245]
When searching through dimension values in the filter tile, we get random exceptions. The following error is in the historical logs:

```
java.lang.IllegalArgumentException: Can't construct empty OrFilter (the universe does not exist)
at io.druid.segment.filter.OrFilter.<init>(OrFilter.java:43)
at io.druid.segment.filter.ExtractionFilter.getBitmapIndex(ExtractionFilter.java:106)
at io.druid.segment.QueryableIndexStorageAdapter.makeCursors(QueryableIndexStorageAdapter.java:202)
at io.druid.query.topn.TopNQueryEngine.query(TopNQueryEngine.java:75)
at io.druid.query.topn.TopNQueryRunnerFactory$1.run(TopNQueryRunnerFactory.java:76)
at io.druid.query.ReferenceCountingSegmentQueryRunner.run(ReferenceCountingSegmentQueryRunner.java:55)
at io.druid.query.MetricsEmittingQueryRunner$1.accumulate(MetricsEmittingQueryRunner.java:118)
at com.metamx.common.guava.Sequences.toList(Sequences.java:113)
at io.druid.query.BySegmentQueryRunner.run(BySegmentQueryRunner.java:56)
at io.druid.query.MetricsEmittingQueryRunner$1.accumulate(MetricsEmittingQueryRunner.java:118)
at io.druid.query.spec.SpecificSegmentQueryRunner$2$1.call(SpecificSegmentQueryRunner.java:87)
at io.druid.query.spec.SpecificSegmentQueryRunner.doNamed(SpecificSegmentQueryRunner.java:171)
at io.druid.query.spec.SpecificSegmentQueryRunner.access$400(SpecificSegmentQueryRunner.java:41)
at io.druid.query.spec.SpecificSegmentQueryRunner$2.doItNamed(SpecificSegmentQueryRunner.java:162)
at io.druid.query.spec.SpecificSegmentQueryRunner$2.accumulate(SpecificSegmentQueryRunner.java:80)
at io.druid.query.CPUTimeMetricQueryRunner$1.accumulate(CPUTimeMetricQueryRunner.java:81)
at com.metamx.common.guava.Sequences$1.accumulate(Sequences.java:90)
at com.metamx.common.guava.Sequences.toList(Sequences.java:113)
at io.druid.query.ChainedExecutionQueryRunner$1$1$1.call(ChainedExecutionQueryRunner.java:129)
at io.druid.query.ChainedExecutionQueryRunner$1$1$1.call(ChainedExecutionQueryRunner.java:119)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at io.druid.query.PrioritizedListenableFutureTask.run(PrioritizedExecutorService.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
```

The query generated by pivot looks like this:

```
{
  "queryType": "topN",
  "dataSource": "bids",
  "intervals": "2016-06-22T09:21Z/2016-06-23T09:21Z",
  "granularity": "all",
  "context": {
    "timeout": 120000
  },
  "filter": {
    "type": "extraction",
    "dimension": "ad",
    "extractionFn": {
      "type": "cascade",
      "extractionFns": [
        {
          "type": "lookup",
          "lookup": {
            "type": "namespace",
            "namespace": "ad_display_value"
          },
          "retainMissingValue": true
        },
        {
          "type": "javascript",
          "function": "function(d){return (_=d,(_==null)?null:((''+_).toLowerCase().indexOf((''+\"1234\").toLowerCase())>-1));}"
        }
      ]
    },
    "value": "true"
  },
  "dimension": {
    "type": "extraction",
    "dimension": "ad",
    "outputName": "ad",
    "extractionFn": {
      "type": "lookup",
      "lookup": {
        "type": "namespace",
        "namespace": "ad_display_value"
      },
      "retainMissingValue": true
    }
  },
  "aggregations": [
    {
      "name": "MEASURE",
      "type": "count"
    }
  ],
  "metric": "MEASURE",
  "threshold": 101
}
```

**Comment by vogievetsky** [comment]
Looks like this a race condition in Druid that happens with filters on extraction functions that is triggered if the lookup updates just at the right time.

This is fixed in Druid 0.9.1 that is coming out soon.
